version: '3.8'

services:
  elysia_api:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    restart: always
    # TODO: use environment variables
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo_user:mongo_password@elysia_mongo_db:27017/test_db
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    depends_on:
      - elysia_mongo_db
    networks:
      - elysia-network

  elysia_mongo_db:
    image: mongo
    volumes:
      - ./database/data:/data/db
      - ./src/database_connection/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # TODO: use environment variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_INITDB_DATABASE=test_db
    ports:
      - '27017:27017'
    networks:
      - elysia-network

networks:
  elysia-network:
